config/routes.rb
Rails.application.routes.draw do

  root "posts#index"

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  get '/user_posts', to: 'posts#user_posts', as: :user_posts

  get '/sign_up', to: 'users#new', as: :sign_up  
  get '/users', to: 'users#new', as: :users  
  
  resources :users, only: [:new, :create]


  resources :sessions, only: [:new, :create, :destroy]
  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body,
  presence: { message: "No puede estar en blanco"}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  validates :title,
  :body,
  presence: { message: "No puede estar vacio"}
  validates :body, length: { minimum: 250 , message: 'El minimo de caracteres es 250'}
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :posts
  has_many :comments
  
  #Validations
  validates :password,
            length: { minimum: 6 , message: 'El minimo de caracteres es 6'},
            confirmation: {message: 'Debes confirmar tu contraseña'}
  
  validates :username,
            uniqueness: {message: "Ya esta en uso"} ,
            length: { minimum: 6, message: 'es demasiado corto, el minimo de caracteres es 6' },case_sensitive: false
  
  validates :email,
            uniqueness: {message: "Ya esta en uso"},
            presence: { message: "No puede estar en blanco"},case_sensitive: false

  validates :username,
            :last_name,
            :first_name ,
            presence: { message: "No puede estar vacio"}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_login  

  private
  
  def not_authenticated
    flash[:warning] = 'No estas autorizado para esta pagina'
    redirect_to log_in_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:create, :destroy]
  def create
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:success] = "Comentario Eliminado"
      redirect_to post_path(@post)
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    if @comment.destroy
      flash[:success] = "Comentario Borrado"
      redirect_to post_path(@post)      
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)    
  end

  def set_post
    @post = Post.find(params[:post_id])    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]
  before_action :user_post, only: [:edit,:update,:destroy]
  before_action :set_post, only: [:show]
  
  def index
    @posts = Post.order('created_at DESC').paginate(:page => params[:page], :per_page => 5)    
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:success] = "Post Creado"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comments = @post.comments
    @comment = @post.comments.build
  end

  def user_posts
    @posts= current_user.posts.order('created_at DESC').paginate(:page => params[:page], :per_page => 5) 
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
      flash[:success] = "Post Editado"
    else
      render :edit
    end
  end
  def destroy
    if current_user == @post.user
      if @post.destroy
        flash[:success] = "Post Eliminado"        
        redirect_to root_path
      end  
    end
  end
  private

  def set_post
    @post = Post.find(params[:id])
  end
  def user_post
    @post = current_user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]
  
  def new
  end
  
  def create
    if login(params[:email], params[:password])
      flash[:success] = 'Bienvenido!'
      redirect_to root_path
    else
      flash[:warning] = 'Correo o contraseña incorrectos'
      redirect_to log_in_path
    end
  end

  def destroy
    logout
    flash[:success] = 'CHAOOOO!'
    redirect_to root_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      login(params[:user][:email], params[:user][:password])
      flash[:success] = 'Welcome!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      login(params[:user][:email], params[:user][:password])
      flash[:success] = 'Bienvenido!'
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
                                       no_intra_emphasis: true,
                                       fenced_code_blocks: true,
                                       disable_indented_code_blocks: true,
                                       autolink: true,
                                       tables: true,
                                       underline: true,
                                       highlight: true
                                      )
    return markdown.render(text).html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>


    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>   
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>    
    
  </head>

  <body>
    <%=render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_comments.html.erb
<% @comments.each do |comment| %>
    <% if comment.user %>
      <div class="comments">
        <% if current_user == comment.user %>
          <div class="actions">
            <%= link_to [comment.post, comment], :confirm => 'Seguro?', :method => :delete do %>
            <button type="button" class="close" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            <% end %>
          </div>
        <% end %>
        <div class="box">
          <p>
            <%= markdown(comment.body) %>
          </p>
          <div class="box-footer">
            <div class="user-info">
              Creado por: <a href="javascript:void(0);"><%= comment.user.username %></a>, hace <%= time_ago_in_words (@post.created_at)%>
            </div>  
          </div>
        </div>
      </div>
    <% end %>
<% end %>

app/views/posts/_comments_form.html.erb
<%= form_for([@comment.post, @comment]) do |f| %>
  <%=render 'shared/errors', object: f.object%>
  <div class="comment-form">
    <div class="box">
      <div class="form-group">
          <%= f.text_area :body, class: 'form-control', placeholder: 'Agrega un comentario.....', required: true %>          
      </div>
      <small>** Acepta MarkDown **</small><br>
      <div class="text-align-center">
        <%= f.submit 'Comentar', class: 'btn btn-primary' %>          
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-md-10 mx-auto">
      <div class="form-group">
        <%= f.label :title, 'Titulo' %>
        <%= f.text_field :title, class: 'form-control'%>
      </div>
      <div class="form-group">
        <%= f.label :body, 'Cuerpo' %>
        <%= f.text_area :body, class: 'form-control', rows: 25  %>
      </div>
      <div class="text-center">
        <%= f.submit action, class: 'btn  btn-primary' %>          
        <%= link_to  "Cancelar", :back, class: 'btn btn-secondary'%>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post_actions.html.erb
<div class="text-center">
  <%= link_to 'Editar', edit_post_path(post), class: 'btn btn-primary'%>
  <%= link_to 'Borrar', post_path(post), method: :delete, data: { confirm: 'Estas seguro?' }, class: 'btn btn-secondary'%>  
</div>

app/views/posts/_posts.html.erb
<header class="masthead" style="background-image: url('/assets/home-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Super Blog</h1>
          <span class="subheading">My clean blog example</span>
        </div>
      </div>
    </div>
  </div>
</header>
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <% @posts.each do |post| %>
        <div class="post-preview">
          <%= link_to post_path(post) do %>          
            <h2 class="post-title">
              <%= post.title.capitalize!%>
            </h2>
          <% end %>
          <p class="post-meta">Publicado por
            <a href="javascript:void(0);"><%=post.user.username%></a>
            <%= time_ago_in_words (post.created_at)%>
          </p>
        </div>
        <hr>      
      <%end%>    
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<header class="masthead" style="background-image: url('/assets/home-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Editar Post</h1>
        </div>
      </div>
    </div>
  </div>
</header>
<div id="register">
  <%= form_for @post do |f| %>
  <div class="row">
      <div class="col-lg-6 col-md-10 mx-auto">
        <%=render 'shared/errors', object: f.object%>
      </div>
  </div>
    <%=render 'form', f: f , action: 'Editar'%>
  <%end%>
</div>  

app/views/posts/index.html.erb
<%= render 'posts'%>

app/views/posts/new.html.erb
<header class="masthead" style="background-image: url('/assets/home-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Nuevo Post</h1>
        </div>
      </div>
    </div>
  </div>
</header>
<div id="register">
  <%= form_for @post do |f| %>    
    <div class="row">
      <div class="col-lg-6 col-md-10 mx-auto">
        <%=render 'shared/errors', object: f.object%>          
      </div>
    </div>
    <%=render 'form', f: f ,action: 'Crear'%>
  <%end%>
</div>  

app/views/posts/show.html.erb
<header class="masthead" style="background-image: url('/assets/post-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-heading">
          <h1><%=@post.title.capitalize!%></h1>
          <span class="meta">Creado por
            <a href="javascript:void(0);"><%=@post.user.username%></a>
            hace <%= time_ago_in_words (@post.updated_at)%></span>
        </div>
      </div>
    </div>
  </div>
</header>
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <%=markdown(@post.body)%>
        <hr>
      </div>
    </div>
  </div>
</article>
<div class="row">
  <div class="col-lg-8 col-md-10 mx-auto">    
    <% if current_user == @post.user%>          
      <div class="post-actions">
        <%=render 'post_actions', post: @post %>          
      </div>
    <%end%>
    <div class="post-comments">
      <%= render 'comments'%>
      <% if current_user %>
        <%= render 'comments_form'%>    
      <% end %>
    </div>
  </div>
  <div class="cell"></div>
</div>

app/views/posts/user_posts.html.erb
<%= render 'posts'%>

app/views/shared/_errors.html.erb
<%if !object.errors.blank?%>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    
    Verifica los campos
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_nav-login.html.erb
<%= form_tag sessions_path ,class: '', method: :post do %>
  </br></br>
  <div class="container-fluid">
    <div class="form-group">
      <%= label_tag :email, "Correo electronico" %>    
      <%= email_field_tag :email, nil, class: 'form-control', required: true, placeholder: 'Correo electronico' %>  
    </div>
    <div class="form-group">
        <%= label_tag :email, "Contraseña" %>    
        <%= password_field_tag :password, nil, class: 'form-control', required: true, placeholder: 'Contraseña' %>  
    </div>
    <%= submit_tag 'Log In', class: 'btn btn-primary' %>          
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <%= link_to  "Super blog", root_path, class: 'navbar-brand' %>    
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fa fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <% if current_user %>
        <li class="nav-item"><%= link_to  "Nuevo Post", new_post_path, class: "nav-link" %></li>
        <li class="nav-item"><a class="nav-link" href="javascript:void(0);"><%= current_user.username %></a></li>
          <li class="nav-item"><%= link_to 'Log Out', log_out_path, method: :delete, class: "nav-link" %></li>
        <% else %>
          <li class="nav-item"><%= link_to  "Registrarse", sign_up_path, class: "nav-link" %></li></li>
          <li class="nav-item"><%= link_to  "Iniciar Sesión", log_in_path, class: "nav-link" %></li></li>
          <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/new.html.erb
<header class="masthead" style="background-image: url('/assets/home-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Registro de usuario</h1>
        </div>
      </div>
    </div>
  </div>
</header>
<div class="register-form container">
  <%= form_for @user do |f| %>
    <div class="row">
      <div class="col-md-12">
        <%= render 'shared/errors', object: f.object%>          
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6 col-md-10 mx-auto">
        <div class="form-group" >
          <%= f.label :first_name, 'Primer Nombre' %>
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>
      </div>
      <div class="col-lg-6 col-md-10 mx-auto">
        <div class="form-group" >
          <%= f.label :last_name , 'Apellido'%>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>        
      </div>
      <div class="col-lg-6 col-md-10 mx-auto">
        <div class="form-group" >
          <%= f.label :username,'Usuario'%>
          <%= f.text_field :username, class: 'form-control' %>
        </div>
      </div>
      <div class="col-lg-6 col-md-10 mx-auto">
        <div class="form-group" >
          <%= f.label :email, 'Correo'%>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
      </div>
      <div class="col-lg-6 col-md-10 mx-auto">
        <div class="form-group" >
          <%= f.label :password, 'Contraseña' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        </div>
        <div class="col-lg-6 col-md-10 mx-auto">
          <div class="form-group" >
            <%= f.label :password_confirmation, 'Confirmar contraseña' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
        </div>
      </div>
      <div class="text-center">
        <%= f.submit 'Registrarse', class: 'btn btn-primary' %>
        <%= link_to  "Cancelar", root_path, class: 'btn btn-secondary' %>
      </div>    
    </div>
  <% end %>
</div>